# bacon configuration
# https://dystroy.org/bacon/

[jobs.check]
command = ["cargo", "check", "--release", "--color", "always"]
need_stdout = false

[jobs.clippy]
command = ["cargo", "clippy", "--release", "--color", "always"]
need_stdout = false

[jobs.build]
command = ["cargo", "build", "--release", "--color", "always"]
need_stdout = false

[jobs.test]
command = ["cargo", "test", "--release", "--color", "always"]
need_stdout = true
