mod barriers;
mod definition;
mod edges;
mod floors;
mod generation;
mod grid;
mod helpers;
mod lights;
mod mask;
pub(crate) mod material_rules;
mod pressure_plates;
mod ramps;
mod segments;
mod trim;
mod walls;

pub use common::physics::OpenBarrierKinds;
pub use generation::generate_map;
pub use helpers::grid_coords_from_position;
pub use pressure_plates::compute_open_barrier_kinds_system;
