[package]
name = "common"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
bevy = { workspace = true, features = ["bevy_log"] }
bevy_ecs = "0.19"
bevy_math = "0.19"
bevy_time = "0.19"
bincode.workspace = true
renet.workspace = true
anyhow.workspace = true
rapier3d.workspace = true
serde.workspace = true
serde_json.workspace = true
